# Generated by Django 5.2 on 2025-05-14 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('client_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('DEBT', 'Debt'), ('CREDIT', 'Credit')], max_length=20)),
                ('account_status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FREEZE', 'Freeze')], max_length=50)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('transaction_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], max_length=50)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.client')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_operations', to='api.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_operations', to='api.account')),
            ],
        ),
    ]
