"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Quick-start development settings - unsuitable for production

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent       # Build paths inside the project like this: BASE_DIR / 'subdir'.

SECRET_KEY = 'django-insecure-y2i^d%7-ecq=qbtn-_zc9xp$hk9zy$_2rgm8h2oy1mg1@wm#d6'   # SECURITY WARNING: keep the secret key used in production secret!
DEBUG = True        # SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'api',
    'import_export',
    'rest_framework',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOW_ALL_ORIGINS = True   # più generale
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = True  # serve perché backend e frontend stanno su indirizzi diversi

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
]

SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Or False, quando chiudo il browser elimina la sessione cookie
SESSION_COOKIE_AGE = 3600  # durata 30 minuti
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Usa il database per le sessioni

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# https://docs.djangoproject.com/en/5.2/howto/static-files/
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field